export interface ModuleCatalogEntry {
  key: string;
  name: string;
  description: string;
  version: string;
  dependencies: string[];
  requiresConfig: boolean;
}

export const MODULE_CATALOG: ModuleCatalogEntry[] = [
  {
    key: 'auth',
    name: 'Authentication',
    description: 'Login, tokens, and sessions',
    version: '1.0.0',
    dependencies: [],
    requiresConfig: false,
  },
  {
    key: 'users',
    name: 'Users',
    description: 'User profiles and memberships',
    version: '1.0.0',
    dependencies: [],
    requiresConfig: false,
  },
  {
    key: 'roles',
    name: 'Roles',
    description: 'Role-based access control',
    version: '1.0.0',
    dependencies: [],
    requiresConfig: false,
  },
  {
    key: 'permissions',
    name: 'Permissions',
    description: 'Granular permissions per Organization',
    version: '1.0.0',
    dependencies: [],
    requiresConfig: false,
  },
  {
    key: 'Organizations',
    name: 'Organizations',
    description: 'Organization management and membership',
    version: '1.0.0',
    dependencies: [],
    requiresConfig: false,
  },
  {
    key: 'settings',
    name: 'Settings',
    description: 'Global products configuration',
    version: '1.0.0',
    dependencies: [],
    requiresConfig: false,
  },
  {
    key: 'organizations',
    name: 'Organizations',
    description: 'Organization management and membership',
    version: '1.0.0',
    dependencies: [],
    requiresConfig: false,
  },
  {
    key: 'devices',
    name: 'Devices',
    description: 'Device access and audit',
    version: '1.0.0',
    dependencies: [],
    requiresConfig: false,
  },
  {
    key: 'products',
    name: 'Products',
    description: 'Productos y cat�logo',
    version: '1.0.0',
    dependencies: [],
    requiresConfig: false,
  },

  {
    key: 'uom',
    name: 'Units of Measure',
    description: 'Units of measure and conversions',
    version: '1.0.0',
    dependencies: [],
    requiresConfig: false,
  },
  {
    key: 'providers',
    name: 'Providers',
    description: 'Supplier management',
    version: '1.0.0',
    dependencies: [],
    requiresConfig: false,
  },
  {
    key: 'price-lists',
    name: 'Price Lists',
    description: 'Pricing and discounts',
    version: '1.0.0',
    dependencies: [],
    requiresConfig: false,
  },
  {
    key: 'warehouses',
    name: 'Warehouses',
    description: 'Warehouse locations and stock zones',
    version: '1.0.0',
    dependencies: [],
    requiresConfig: false,
  },
  {
    key: 'locations',
    name: 'Locations',
    description: 'Branches and warehouses setup',
    version: '1.0.0',
    dependencies: ['companies'],
    requiresConfig: true,
  },
  {
    key: 'inventory',
    name: 'Inventory',
    description: 'Stock ledger and projections',
    version: '1.0.0',
    dependencies: [],
    requiresConfig: true,
  },
  {
    key: 'inventory-counts',
    name: 'Inventory Counts',
    description: 'Physical counts and reconciliation',
    version: '1.0.0',
    dependencies: [],
    requiresConfig: false,
  },
  {
    key: 'purchases',
    name: 'Purchases',
    description: 'Purchase orders and receipts',
    version: '1.0.0',
    dependencies: [],
    requiresConfig: false,
  },
  {
    key: 'pos',
    name: 'Point of Sale',
    description: 'Sales, carts, and payments',
    version: '1.0.0',
    dependencies: [],
    requiresConfig: true,
  },
  {
    key: 'prepaid',
    name: 'Prepaid',
    description: 'Recargas y saldo por proveedor',
    version: '1.0.0',
    dependencies: ['pos'],
    requiresConfig: false,
  },
  {
    key: 'customers',
    name: 'Customers',
    description: 'Customer records and credit',
    version: '1.0.0',
    dependencies: [],
    requiresConfig: false,
  },
  {
    key: 'accounting',
    name: 'Accounting',
    description: 'Accounts, journals, and taxes',
    version: '1.0.0',
    dependencies: [],
    requiresConfig: true,
  },
  {
    key: 'reports',
    name: 'Reports',
    description: 'Reporting and BI exports',
    version: '1.0.0',
    dependencies: [],
    requiresConfig: false,
  },
  {
    key: 'health',
    name: 'Health',
    description: 'Health checks and status',
    version: '1.0.0',
    dependencies: [],
    requiresConfig: false,
  },
  {
    key: 'realtime',
    name: 'Realtime',
    description: 'Realtime notifications',
    version: '1.0.0',
    dependencies: [],
    requiresConfig: false,
  },
  {
    key: 'chat',
    name: 'Chat',
    description: 'Internal messaging',
    version: '1.0.0',
    dependencies: [],
    requiresConfig: false,
  },
];
